nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Une Api pour Mobile!
            version: 2.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: Permet d'obtenir le token JWT.
                    requestBody:
                          description: Crée un nouveau token JWT
                          content:
                             application/json:
                                 schema:
                                     $ref: '#/components/schemas/Credentials'
                    response:
                       '200':
                            description: Récupère le token JWT
                            content:
                                  application/json:
                                        schema:
                                            $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@bilemo.com
                        password:
                            type: string
                            default: password
            securitySchemes:
               bearerAuth:
                   type: apiKey
                   in: header
                   name: Authorization # or another header name
        securitySchemes:
           bearerAuth:
                type: apiKey
                in: header
                name: Authorization # or another header name
        security:
            - bearerAuth: []                    
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
